name: Downcase

on: 
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
        echo "AUTHOR=${GITHUB_ACTOR}" >> ${GITHUB_ENV}
        echo "ID=${GITHUB_ACTOR_ID}" >> ${GITHUB_ENV}
        echo "REF=${GITHUB_REF}" >> ${GITHUB_ENV}
        echo "REF_SHORT=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        echo "SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
    
    - name: Echo
      run: |
        echo "${GITHUB_ENV}"
        echo "${REPO}"
        echo "${AUTHOR}"
        echo "${ID}"
        echo "${REF}"
        echo "${REF_SHORT}"
        echo "${SHA}"