name: Negation example

on:
  push:
    paths: 
      - "website/(?!README.md).**"

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Step
        run: |
          ls -la
          ls -la website/