name: Test export env

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORD: ${GITHUB_REPOSITORY#*/}"-dev"
    steps:
      - name: Echo
        run: echo $WORD
      - name: Echo
        run: echo $WORD
