name: Test export env

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Export
        run: |
          export word=${GITHUB_REPOSITORY#*/}"-dev"
          echo $word
