name: Workflow Run

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Manual workflow']
    types: [completed]
    branches:
      - 'main'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Send run
      run: echo "Hello Run workflow"