name: Zap Proxy

on: [workflow_dispatch]

jobs:
  Scan:
    runs-on: ubuntu-22.04 
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'https://stage-decimated-webstore.blaize.technology/'
